import { createSlice } from "@reduxjs/toolkit";
import {
  aliens,
  badSeed,
  csugar,
  davidTrouble,
  dinoCatch,
  dlove,
  ilove,
  pyoga,
  sboy,
  spacebooks,
} from "../../assets";

const initialState = {
  seriesSelected: "Peppa Pig",
  topTen: [
    {
      title: "There's Coriander in my Sugar Pot!",
      image: csugar,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: true,
      link: "https://www.amazon.in/",
    },
    {
      title: "Space Boy",
      image: sboy,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: false,
      link: "https://www.amazon.in/",
    },
    {
      title: "I Love My New Toy!",
      image: ilove,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-2",
      isNewArrival: false,
      link: "https://www.amazon.in/",
    },
    {
      title: "Dinosaur Love Underpants",
      image: dlove,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: false,
      link: "https://www.amazon.in/",
    },
    {
      title: "Peppa Loves Yoga",
      image: pyoga,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-2",
      isNewArrival: true,
      link: "https://www.amazon.in/",
    },
    {
      title: "Aliens love Dinopants",
      image: aliens,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-2",
      isNewArrival: true,
      link: "https://www.amazon.in/",
    },
    {
      title: "The Bad Seed",
      image: badSeed,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-2",
      isNewArrival: true,
      link: "https://www.amazon.in/",
    },
    {
      title: "Book About Space",
      image: spacebooks,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-2",
      isNewArrival: true,
      link: "https://www.amazon.in/",
    },
    {
      title: "How to Catch a Dinosaur",
      image: dinoCatch,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-2",
      isNewArrival: true,
      link: "https://www.amazon.in/",
    },
    {
      title: "David Gets in Trouble",
      image: davidTrouble,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-2",
      isNewArrival: true,
      link: "https://www.amazon.in/",
    },
  ],
  allBooks: [
    {
      title: "There's Coriander in my Sugar Pot!",
      image: csugar,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Space Boy",
      image: sboy,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Science",
    },
    {
      title: "I Love My New Toy!",
      image: ilove,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-1",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Dinosaur Love Underpants",
      image: dlove,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Dinosaur",
    },
    {
      title: "Peppa Loves Yoga",
      image: pyoga,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-1",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Peppa Pig",
    },
    {
      title: "Aliens love Dinopants",
      image: aliens,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-1",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Aliens",
    },
    {
      title: "The Bad Seed",
      image: badSeed,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-1",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Book About Space",
      image: spacebooks,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-1",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Space",
    },
    {
      title: "How to Catch a Dinosaur",
      image: dinoCatch,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "9-12",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Dinosaur",
    },
    {
      title: "David Gets in Trouble",
      image: davidTrouble,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "9-12",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "David",
    },
    {
      title: "There's Coriander in my Sugar Pot!",
      image: csugar,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Space Boy",
      image: sboy,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Science",
    },
    {
      title: "I Love My New Toy!",
      image: ilove,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "6-9",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Dinosaur Love Underpants",
      image: dlove,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "1-3",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Dinosaur",
    },
    {
      title: "Peppa Loves Yoga",
      image: pyoga,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "6-9",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Peppa Pig",
    },
    {
      title: "Aliens love Dinopants",
      image: aliens,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "1-3",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Aliens",
    },
    {
      title: "The Bad Seed",
      image: badSeed,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "12+",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Book About Space",
      image: spacebooks,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "12+",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Science",
    },
    {
      title: "How to Catch a Dinosaur",
      image: dinoCatch,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "9-12",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Dinosaur",
    },
    {
      title: "David Gets in Trouble",
      image: davidTrouble,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-1",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "David",
    },
    {
      title: "There's Coriander in my Sugar Pot!",
      image: csugar,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "6-9",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Space Boy",
      image: sboy,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "12+",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Science",
    },
    {
      title: "I Love My New Toy!",
      image: ilove,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "3-6",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Dinosaur Love Underpants",
      image: dlove,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "9-12",
      isNewArrival: false,
      link: "https://www.amazon.in/",
      series: "Dinosaur",
    },
    {
      title: "Peppa Loves Yoga",
      image: pyoga,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "9-12",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Peppa Pig",
    },
    {
      title: "Aliens love Dinopants",
      image: aliens,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "12+",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Under Pants",
    },
    {
      title: "The Bad Seed",
      image: badSeed,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "12+",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Habits",
    },
    {
      title: "Book About Space",
      image: spacebooks,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "12+",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Science",
    },
    {
      title: "How to Catch a Dinosaur",
      image: dinoCatch,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "1-3",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "Dinosaur",
    },
    {
      title: "David Gets in Trouble",
      image: davidTrouble,
      desc: "All mamma wants on her special day is a little bit of peace, love, and cleanliness...",
      rating: "4.3",
      peopleRead: 1234,
      age: "0-1",
      isNewArrival: true,
      link: "https://www.amazon.in/",
      series: "David",
    },
  ],
  bookTitle: [
    {
      title: "Peppa Pig",
      image: pyoga,
    },
    {
      title: "Science",
      image: sboy,
    },
    {
      title: "Habits",
      image: badSeed,
    },
    {
      title: "Dinosaur",
      image: dinoCatch,
    },
    {
      title: "Aliens",
      image: aliens,
    },
    {
      title: "David",
      image: davidTrouble,
    },
  ],
};
const bookSlice = createSlice({
  name: "books",
  initialState,
  reducers: {
    changeSeries: (state, { payload }) => {
      state.seriesSelected = payload;
    },
  },
});
export const { changeSeries } = bookSlice.actions;
export default bookSlice.reducer;
